
## Ansible Playbook to ping servers in the 'frontend' group

- name: ping the sever
  hosts: frontend # specify which group of servers to target
  tasks:
    - name: ping the server to check connectivity
      ansible.builtin.ping: