# Here working with loops in ansible playbook
# This playbook will demonstrate how to use loops in Ansible playbooks

- name: Installin the packages using loops
  hosts: localhost
  connection: local
  tasks:
    - name: Printing the packages names
      ansible.builtin.package:
         name: "{{ item}}" # Using loop variable 'item' to refer to the current package name
         state: latest
      loop:
        - nginx
        - mysql
        - mongodb
        - redis

# Here we are using the debug module to print numbers from 1 to 5
# The 'loop' directive is used to iterate over a list of items and perform the same task for each item in the list