# Here i'm working with functions in ansible playbook
# This playbook will demonstrate how to use functions in Ansible playbooks
- name: using the functions in ansible playbooks
  hosts: localhost
  connection: local
  vars: 
    technologies: DevOps, Cloud, Automation, Containerization # String variable containing a list of technologies
    name: "Ajay Naik Banoth"
    gmail: "Banoth.Ajay@gmail.com "
    ip_address: "19256.168.1.1"

    # Here dictionary == map in ansible playbook
    tags:
      Application: Web
      Environment: Production


    # adding the list of tags in the dictionary variable 'tags' with key-value pairs representing the tag name and its value
    listTags:
    - key: "Application"
      value: "Web"
    - key: "Environment"
      value: "Production"
  tasks:
    - name: Using the default variable in ansible playbook
      ansible.builtin.debug:
        msg: "My name is {{ name | default ('Ansible')}}" # Using the 'default' filter to provide a default value for the variable 'name' if it is not defined


# String to list conversion using the 'split' filter
    - name: Converting string to list using split function
      ansible.builtin.debug:
        msg: "The technologies I am interested in are: {{ technologies.split(', ') }}" 
        # Using the 'split' filter to convert the string variable 'technologies' into a list by splitting it at the comma and space


# dictionary to list conversion using the 'dict2items' filter
    - name: Converting dictionary to list using dict2items function
      ansible.builtin.debug:
        msg: "The tags for my application are: {{ tags | dict2items }}" 
        # Using the 'dict2items' filter to convert the dictionary variable 'tags' into a list of dictionaries, where each dictionary contains a key and value from the original dictionary 
   
# converting the list into maps or dictionaries using the 'items2dict' filter
    - name: Converting list to dictionary using items2dict function
      ansible.builtin.debug:
        msg: "The tags for my application are: {{ listTags | items2dict(key_name='key', value_name='value') }}" 
       # Using the 'items2dict' filter to convert the list of dictionaries variable 'listTags' back into a dictionary, where the 'key_name' parameter specifies the key to use for the dictionary and the 'value_name' parameter specifies the value to use for the dictionary


# Here i'm reading the yaml files and conveting them into variables using the 'lookup' plugin and the 'from_yaml' filter
    - name: read the yaml files and convert it into variable
      ansible.builtin.set_fact:
        student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml  }}" 
        # Using the 'to_json' filter to convert the dictionary variable 'tags' into a JSON string representation of the dictionary

# Here i'm using the 'to_json' filter to convert the dictionary variable 'tags' into a JSON string representation of the dictionary
    - name: Converting dictionary to JSON string using to_json function
      ansible.builtin.debug:
        msg: "The tags for my application in JSON format are: {{ student_yaml | to_json }}"

# Here i'm using the copy plugin to copy the JSON in to a file
    - name: Copying the JSON string to a file
      ansible.builtin.copy:
        dest: ./student-data.json # Destination path where the JSON string will be copied
        content: "{{ student_yaml | to_nice_json }}"
        # Using the 'copy' module to write the JSON string representation of the 'student_yaml' variable to a file located at '/tmp/student-data.json'

# Working on upper case and lower case functions in ansible playbook
    - name: Converting string to upper case using upper function
      ansible.builtin.debug:
        msg: "My name in upper case is: {{ name | upper }}" 
        # Using the 'upper' filter to convert the string variable 'name' to upper case

    - name: Converting string to lower case using lower function
      ansible.builtin.debug:
        msg: "My gmail in lower case is: {{ gmail | lower }}" 
        # Using the 'lower' filter to convert the string variable 'gmail' to lower case        

 # Checking the ip address is valid or not using the 'ipaddr' filter
    - name: Checking if the IP address is valid using ipaddr function
      ansible.builtin.debug:
        msg: "Is the IP address {{ ip_address }} valid? {{ ip_address | ansible.utils.ipv4 }}" 
        # Using the 'ipaddr' filter to check if the string variable 'ip_address' is a valid IP address


# working on shell and command module in ansible playbook
    # - name: grep for root
    #   ansible.builtin.command: "cat /etc/passwd | grep root"
    #   register: grep_result # Registering the output of the command to a variable 'grep_result'

    - name: grep for root using shell module
      ansible.builtin.command: "cat /etc/passwd | grep root" # Using the 'shell' module to execute the command "cat /etc/passwd | grep root" on the target host and capture the output
      register: grep_result # Registering the output of the command to a variable 'grep_result'


    - name: Displaying the result of the grep command
      ansible.builtin.debug:
        msg: "The result of the grep command is: {{ grep_result }}" 
        # Using the 'debug' module to display the standard output of the registered variable 'grep_result'

# this command is for redirecting the output of the command to a file
    - name: Redirecting the output of the command to a file
      ansible.builtin.shell: "cat /etc/passwd | grep root > /tmp/grep_result.txt" 
      register: redirect_result 
      # we have to make use of shell command for redirecting the output of the command to a file.
      # Command module does not support the redirection of output to a file.

    - name: Displaying the result of the redirect command
      ansible.builtin.debug:
        msg: "The result of the redirect command is: {{ redirect_result }}" 
        # Using the 'debug' module to display the standard output of the registered variable 'redirect_result'